In [14]:
import numpy as np

# Efficient numeric computation with C primitives
# Efficient collections with vectorized operations
# An integrated and natural Linear Algebra API
# A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

In [15]:
# basics
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])

## Slicing

In [16]:
a[0], a[1]

(1, 2)

In [17]:
a[1:3]

array([2, 3])

In [18]:
a[1:-1]

array([2, 3])

In [19]:
a[::2]

array([1, 3])

In [20]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [22]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [23]:
# types
a.dtype

dtype('int64')

In [24]:
b.dtype

dtype('float64')

In [25]:
np.array([1, 2, 3, 4], dtype=float)  # Legacy: np.float

array([1., 2., 3., 4.])

## Shapes

In [26]:

M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [27]:
M.shape

(2, 3)

In [28]:
M.ndim

2

In [29]:
M.size

6

In [30]:
M1 = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [31]:
print(M1.shape, M1.ndim, M1.size)

(2, 2, 3) 3 12


In [32]:
# in case shape is not consistent -> fallback to Python
strange = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
strange = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
    ]
], dtype=object)   # NEED TO FORCE THAT

In [35]:
strange.shape

(2,)

## Ndim Indexing and Slicing

In [36]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [37]:
A[1]

array([4, 5, 6])

In [38]:
A[1][0]

4

In [39]:
A[1, 0]

4

In [40]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
_.shape

(3, 2)

In [43]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [44]:
A[:2, 2:]

array([[3],
       [6]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[1] = np.array([10, 10, 10])

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [48]:
A[2] = 99

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [50]:
A.sum()

333

In [51]:
A.mean()

37.0

In [52]:
A.std()

43.96463225012679

In [53]:
A.std(axis=0)

array([44.22920101, 43.96210489, 43.69846171])

In [54]:
A.std(axis=1)

array([0.81649658, 0.        , 0.        ])

## Broadcasting

In [55]:
a = np.arange(4)
a + 10

array([10, 11, 12, 13])

In [56]:
b = np.array([10,20,30,40])

In [57]:
a + b

array([10, 21, 32, 43])

In [58]:
a * b

array([  0,  20,  60, 120])

## Boolean masks

In [59]:
a

array([0, 1, 2, 3])

In [60]:
a > 2

array([False, False, False,  True])

In [61]:
a[a > 1]

array([2, 3])

In [62]:
a[~(a > a.mean())]

array([0, 1])

In [63]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [64]:
A = np.random.randint(100, size=(3, 3))

In [65]:
A

array([[67, 80, 42],
       [20,  5, 67],
       [82, 99, 26]])

In [66]:
A > 30

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True, False]])

## Basic algebra

In [67]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

C = np.array([
    [2, 2],
    [3, 3],
    [4, 4]
])

In [68]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [69]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [70]:
B * C  # element-wise (on correct shapes)

array([[12, 10],
       [12,  9],
       [ 8,  4]])

In [71]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [73]:
np.eye(8, 4, k=-4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])